export const PRODUCTSCALENDAR_ACTION_TYPES = {
    FETCH_PRODUCTSCALENDAR_START: 'productscalendar/FETCH_PRODUCTSCALENDAR_START',
    FETCH_PRODUCTSCALENDAR_SUCCESS: 'productscalendar/FETCH_PRODUCTSCALENDAR_SUCCESS',
    FETCH_PRODUCTSCALENDAR_ERROR: 'productscalendar/FETCH_PRODUCTSCALENDAR_ERROR',
}