export const ANALYTICS_ACTION_TYPES = {
    SET_FILTER: 'analytics/SET_FILTER',
    FETCH_ANALYTICS_START: 'analytics/FETCH_ANALYTICS_START',
    FETCH_ANALYTICS_SUCCESS: 'analytics/FETCH_ANALYTICS_SUCCESS',
    FETCH_ANALYTICS_ERROR: 'analytics/FETCH_ANALYTICS_ERROR',
}